name: eah_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and basic dependencies
  - python=3.9  # Required by pycoral
  - pip
  - numpy>=1.23.0
  - pillow>=9.5.0
  - matplotlib>=3.7.0
  
  # Jupyter environment
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  - notebook>=7.0.0
  
  # Hardware-specific dependencies for Raspberry Pi
  - pip:
      # TensorFlow Lite and Coral
      - --extra-index-url https://google-coral.github.io/py-repo/
      - pycoral~=2.0
      - tflite-runtime~=2.5.0
      
      # OpenCV (headless version for better performance)
      - opencv-python-headless>=4.8.0
      
      # Core ML framework - using TF nightly for better ARM support
      - tensorflow-aarch64>=2.14.0
      
      # Utility packages
      - tqdm>=4.65.0
      - psutil>=5.9.0  # For monitoring system resources
      
      # Web server for remote access
      - jupyter-server-proxy>=4.1.0  # For proxying Jupyter through nginx if needed
      
      # Model dependencies
      - transformers>=4.30.0  # For SegFormer
      - keras>=3.0.0
  - kagglehub>=0.2.0
  
  # Model-specific dependencies
  - keras-cv>=0.5.10