name: eah_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  # Pin Python version if needed
  - python=3.9
  
  # Conda packages
  - pip
  - numpy>=1.23.0
  - opencv>=4.7.0
  - pillow>=9.5.0
  - matplotlib>=3.7.0
  - jupyterlab
  - pip:
      # Core dependencies
      - tensorflow>=2.12.0
      - tensorflow-hub>=0.13.0
      - tensorflow-datasets>=4.9.0
      - tensorflow-io-gcs-filesystem>=0.24.0
      - kagglehub>=0.2.0
      - transformers>=4.30.0
      
      # Model-specific dependencies
      - keras-cv>=0.5.10
      - keras-hub>=0.20.0
      #- git+https://github.com/bonlime/keras-deeplab-v3-plus.git
      
      # Utility packages
      - tqdm>=4.65.0
