name: eah_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  # Pin Python version if needed
  - python=3.9
  
  # Conda packages
  - pip
  - numpy
  - opencv
  - pip:
      # Below are pip-based packages that conda might not have at the desired versions
      - tensorflow>=2.8.0
      - tensorflow-hub>=0.12.0
      - tqdm~=4.65.0  # Pinned to match openxlab requirement
      - tensorflow-io-gcs-filesystem>=0.24.0  # For TF Hub models
      - keras-cv>=0.5.10
      - git+https://github.com/bonlime/keras-deeplab-v3-plus.git  # For DeepLab models
      # Add any other pip-specific dependencies if needed
